### ISSUE TITLE
Log: Unexpected error fetching

### ISSUE THREAD

**Issue by milandzuris** [djtimca/hasatellitetracker#13]
Hi i have this many times in Log

This error originated from a custom integration.

Logger: custom_components.satellitetracker
Source: helpers/update_coordinator.py:315
integration: N2YO Satellite Tracker (documentation, issues)
First occurred: May 14, 2024 at 13:10:21 (59 occurrences)
Last logged: 11:44:20

Unexpected error fetching International Space Station (ISS) data
Unexpected error fetching skCUBE data
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/n2yoasync/__init__.py", line 82, in get_api
    async with self.session.get(
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 608, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 976, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 640, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/satellitetracker/__init__.py", line 252, in _async_update_data
    positions_data = await self.api.get_positions(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/n2yoasync/__init__.py", line 155, in get_positions
    response = await self.get_api(f"positions/{id}/{latitude}/{longitude}/{altitude}/{seconds}")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/n2yoasync/__init__.py", line 88, in get_api
    raise ConnectionError(error)
ConnectionError: Server disconnected

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/satellitetracker/__init__.py", line 275, in _async_update_data
    raise PlatformNotReady from error
homeassistant.exceptions.PlatformNotReady: Server disconnected

**Comment by djtimca** [comment]
Appears to be related to your ability to access the server for updates. Not the most graceful error handling to be fair, but this isn't a code issue, it's network / connectivity.
